apiVersion: v1
kind: Service
metadata:
  name: {{ include "opa-service.fullname" . }}
  labels:
    {{- include "opa-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "opa-service.selectorLabels" . | nindent 4 }}
